name: CI – MATLAB smoke test

on:
  workflow_dispatch:   # lo lanci a mano quando vuoi

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run 1-day simulation + checks
        uses: matlab-actions/run-command@v2
        with:
          command: |
            startup;                                  % path + cartelle output
            [outFN, ~] = run_district_day(32,'scn2_5PV_1BESS.mat');
            assert(isfile(outFN), "Output MAT not found: %s", outFN)
            % opzionale: KPI e figure “headless”
            post_process_day(2023,32,'scn2_5PV_1BESS.mat');
            verify_day_robust;                        % stampa check formali

      - name: Upload artifacts (results/figs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: matlab-results
          path: |
            results/daily/**
            results/summary/**
            figs/**
          if-no-files-found: ignore
          retention-days: 7
