name: CI – MATLAB smoke test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with Git LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Force LFS pull + sanity check
        shell: bash
        run: |
          set -euxo pipefail
          git lfs version
          git lfs fetch --all
          git lfs checkout
          git lfs pull
          echo "=== LFS files ==="
          git lfs ls-files || true
          echo "=== Contenuto data/scenarios ==="
          ls -l data/scenarios || true
          file data/scenarios/scn2_5PV_1BESS.mat || true

      - name: Set up MATLAB (with toolboxes)
        uses: matlab-actions/setup-matlab@v2
        with:
          products: |
            MATLAB
            Statistics and Machine Learning Toolbox

      # (facoltativo) stampa le toolbox installate
      - name: MATLAB ver
        uses: matlab-actions/run-command@v2
        with:
          command: ver

      - name: Run 1-day simulation + checks
        uses: matlab-actions/run-command@v2
        with:
          command: |
            startup;
            [outFN, ~] = run_district_day(32,'scn2_5PV_1BESS.mat');
            assert(isfile(outFN), "Output MAT not found: %s", outFN)
            post_process_day(2023,32,'scn2_5PV_1BESS.mat');
            verify_day_robust;

      - name: Upload artifacts (results + figs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: matlab-results
          path: |
            results/**
            figs/**
          if-no-files-found: ignore
          retention-days: 7
