name: CI – MATLAB smoke test
on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Pre-flight check (what's in the repo?)
        shell: bash
        run: |
          echo "== repo root =="
          ls -lah
          echo "== data =="
          ls -lah data || true
          echo "== data/scenarios =="
          ls -lah data/scenarios || true
          git lfs version || true
          git lfs ls-files || true

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2025a

      - name: Run 1-day simulation + checks
        uses: matlab-actions/run-command@v2
        with:
          command: |
            startup;
            SCN = fullfile('data','scenarios','scn2_5PV_1BESS.mat');
            assert(isfile(SCN), '*** Manca lo scenario: %s (aggiungilo a data/scenarios/)', SCN);
            [outFN, ~] = run_district_day(32, SCN);
            assert(isfile(outFN), 'Output MAT non creato: %s', outFN);
            post_process_day(2023, 32, 'scn2_5PV_1BESS.mat');
            verify_day_robust;

      - name: Upload artifacts (results/figs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: matlab-results
          path: |
            results/daily/**
            results/summary/**
            figs/**
          if-no-files-found: ignore
          retention-days: 7
