name: CI – MATLAB smoke test

on:
  workflow_dispatch:  # lo lanci a mano quando vuoi

permissions:
  contents: read
  actions: write

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run 1-day simulation + checks
        uses: matlab-actions/run-command@v2
        with:
          command: |
            disp('=== DIAG ==='); disp(pwd); dir
            assert(exist('startup','file')==2, 'startup.m non trovato nella repo');
            startup;                      % addpath + crea results/ e figs/
            assert(exist('run_district_day','file')==2, 'run_district_day.m non in path');

            % Simula 1 giorno scenario 2
            [outFN, ~] = run_district_day(32, 'scn2_5PV_1BESS.mat');
            assert(isfile(outFN), sprintf('MAT non creato: %s', outFN));

            % Post-process e check "robusto"
            post_process_day(2023, 32, 'scn2_5PV_1BESS.mat');
            verify_day_robust;

      - name: Upload artifacts (results/figs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: matlab-results
            path: |
              results/daily/**
              results/summary/**
              figs/**
            if-no-files-found: warn
            retention-days: 7
